export const CLIENT_CONFIG = {
  companyName: "U-Assistant",
  companyTagline: "Premium Digital Solutions · Interactive Suite",
  companyLegal: "2026 U-Assistant. All rights reserved.",
  primaryColor: "#f97316",
  logoAccentColor: "#f97316",
  marketRegion: "Australian Metropolitan",
  fencingStandard: "AS-2423 Approved",
  appPassword: "demo2026",
  footerSecurityText: "AS-2423 SECURE VAULT",
  footerSystemText: "SYSTEM v4.1",
  loginFooterText: "U-Assistant © 2026. This secure visualizer environment has been custom-hardened for certified team consultants.",
  companyLegalShort: "U-Assistant",
  regionState: "NSW",
  regionCity: "Sydney",
  proposalIdPrefix: "DEMO",
  companyPhone: "+61 489 996 443",
  companyEmail: "u-assistant.agency@gmail.com",
  companyWebsite: "u-assistant.base44.app",
  companyAddress: "Sydney, Australia",
  companyABN: "00 000 000 000",
  logoFileName: "logo.png",
  quoteValidityDays: 30,
  quoteTerms: "This quote is valid for 30 days from the date of issue. All prices include GST. A 10% deposit is required to confirm booking. Final measurements will be confirmed on-site prior to installation.",
};
